name: weather_test
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  asuka: ^2.2.0
  carousel_slider: ^4.2.1
  collection: ^1.18.0
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_modular: ^6.3.2
  hive: ^2.2.3
  intl: ^0.19.0
  path_provider: ^2.1.2

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true
