name: Flutter CI

# This workflow is triggered on pushes to the repository.

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

# on: push    # Default will running for every branch.

jobs:
  build:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Generate .env
        run: |
          touch .env
          echo { >> .env
          echo \"BASE_URL\"=\"https://api.openweathermap.org/data/2.5/\", >> .env
          echo \"API_KEY\"=\"${{ secrets.API_KEY }}\" >> .env
          echo } >> .env
          cat .env
        working-directory: ./weather_test

      - name: Install dependencies
        run: flutter pub get
        working-directory: ./weather_test

      - name: Format code
        run: dart format --set-exit-if-changed .
        working-directory: ./weather_test

      - name: Statically analyze
        run: flutter analyze .
        working-directory: ./weather_test

      - name: Run Tests
        run: flutter test
        working-directory: ./weather_test

      - name: Build apk.
        run: flutter build apk --release --dart-define-from-file=.env
        working-directory: ./weather_test

      - uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
          working-directory: ./weather_test
